# Generated by Django 2.1.7 on 2020-02-15 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCrud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashier',
            old_name='nama',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='nama',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id_cashier',
            new_name='cashier',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='nama',
            new_name='name',
        ),
    ]
